# Этап сборки (builder)
FROM node:22.14.0-alpine AS builder

# Рабочая директория в контейнере
WORKDIR /app

# 1. Копируем только package.json и package-lock.json (для кэширования)
COPY package.json package-lock.json ./

# 2. Устанавливаем зависимости
RUN npm install

# 3. Копируем остальные файлы проекта
COPY . .

# 4. Собираем приложение
RUN npm run build

# Этап запуска (nginx)
FROM nginx:alpine

# Копируем собранные файлы из builder-этапа
COPY --from=builder /app/dist /usr/share/nginx/html

# (Опционально) Конфиг для SPA (если используете Vue Router)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Заменяем %%WS_SERVER_IP%% на переменную окружения при старте
CMD ["sh", "-c", "sed -i 's|%%WS_SERVER_IP%%|${WS_SERVER_IP:-10.160.160.148}|g; s|%%WS_SERVER_PORT%%|${WS_SERVER_PORT:-8765}|g' /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]

# Открываем порт 80
EXPOSE 80