name: chess316
description: "client for chess robot"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  tcp_socket_connection: ^0.3.1
  provider: ^6.1.1  
  mocktail: ^1.0.0  
  build_runner: ^2.4.0  
  dio: ^5.4.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/